### ISSUE TITLE
Doesn't return a fs.createReadStream similar thing. Error: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by creativesoumik** [jasontbradshaw/tailing-stream#5]
I'm receiving a stream via socket.io.-stream then saving it. I need this module to read the the file which is continuously growing and then push to box.com. Your readme didn't include any example. Can you please show me how this can be done? 

io.on('connection', socket => {
    console.log('connection');     

    ss(socket).on('file', (stream, data) => {
        console.log('>>>Received File Emit at <<<', new Date().toString());
        console.log('data.originalName', data.originalName);

        var streamFileName = './uploads/'+data.originalName;

        stream.pipe(fs.createWriteStream( streamFileName ));
        
         var boxStream = ts.TailingReadableStream (path.join(__dirname, streamFileName),{timeout: 5000});

       function requestCallback(err, res, body) {
            console.log('Request body: ',body);
        }

          var total = 0;
          boxStream.on('data', (chunk) => {

            total += chunk.length;
            var progress = (1.0 * total) / data.size;
            console.log('Box upload progres : ', progress);
          });

          var accessToken = 'hidden';
          var parent_folder_id = 'hidden';

          var r = request.post({
              url: 'https://upload.box.com/api/2.0/files/content',
              headers: { 'Authorization': 'Bearer ' + accessToken }
              }, requestCallback);

          var form = r.form();

          form.append('parent_id', parent_folder_id);
          form.append("file", boxStream);        

    });
});

**Comment by jasontbradshaw** [comment]
Unfortunately I can't be of any help since I haven't used Node seriously in years, and haven't used this module in even longer.

I hope you're able to find an answer to your problem, though!
